
package servidor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InscFechaDespSalida", targetNamespace = "http://servidor/")
public class InscFechaDespSalida_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InscFechaDespSalida faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InscFechaDespSalida_Exception(String message, InscFechaDespSalida faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InscFechaDespSalida_Exception(String message, InscFechaDespSalida faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.InscFechaDespSalida
     */
    public InscFechaDespSalida getFaultInfo() {
        return faultInfo;
    }

}
