
package servidor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorIControladorService", targetNamespace = "http://servidor/", wsdlLocation = "http://10.0.2.15:40000/publicador?wsdl")
public class PublicadorIControladorService
    extends Service
{

    private final static URL PUBLICADORICONTROLADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORICONTROLADORSERVICE_EXCEPTION;
    private final static QName PUBLICADORICONTROLADORSERVICE_QNAME = new QName("http://servidor/", "PublicadorIControladorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.2.15:40000/publicador?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORICONTROLADORSERVICE_WSDL_LOCATION = url;
        PUBLICADORICONTROLADORSERVICE_EXCEPTION = e;
    }

    public PublicadorIControladorService() {
        super(__getWsdlLocation(), PUBLICADORICONTROLADORSERVICE_QNAME);
    }

    public PublicadorIControladorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORICONTROLADORSERVICE_QNAME, features);
    }

    public PublicadorIControladorService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORICONTROLADORSERVICE_QNAME);
    }

    public PublicadorIControladorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORICONTROLADORSERVICE_QNAME, features);
    }

    public PublicadorIControladorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorIControladorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorIControlador
     */
    @WebEndpoint(name = "PublicadorIControladorPort")
    public PublicadorIControlador getPublicadorIControladorPort() {
        return super.getPort(new QName("http://servidor/", "PublicadorIControladorPort"), PublicadorIControlador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorIControlador
     */
    @WebEndpoint(name = "PublicadorIControladorPort")
    public PublicadorIControlador getPublicadorIControladorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "PublicadorIControladorPort"), PublicadorIControlador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORICONTROLADORSERVICE_EXCEPTION!= null) {
            throw PUBLICADORICONTROLADORSERVICE_EXCEPTION;
        }
        return PUBLICADORICONTROLADORSERVICE_WSDL_LOCATION;
    }

}
