
package servidor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SalidasVigentesException", targetNamespace = "http://servidor/")
public class SalidasVigentesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SalidasVigentesException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SalidasVigentesException_Exception(String message, SalidasVigentesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SalidasVigentesException_Exception(String message, SalidasVigentesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.SalidasVigentesException
     */
    public SalidasVigentesException getFaultInfo() {
        return faultInfo;
    }

}
